
const LOGIN_API_REQUEST = 'LOGIN_API_REQUEST'
const LOGIN_API_SUCCESS = 'LOGIN_API_SUCCESS'
const LOGIN_API_ERROR = 'LOGIN_API_ERROR'

const MAPDATA_API_REQUEST = 'MAPDATA_API_REQUEST'
const MAPDATA_API_SUCCESS = 'MAPDATA_API_SUCCESS'
const MAPDATA_API_ERROR = 'MAPDATA_API_ERROR'

const SVG_LOADED = 'SVG_LOADED'
const SVG_UNLOADED = 'SVG_UNLOADED'
const SVG_CLICK = 'SVG_CLICK'

const CONTENT_SHOW = 'CONTENT_SHOW'
const CONTENT_NOT_SHOW = 'CONTENT_NOT_SHOW'


const DRAWER_SHOW = 'DRAWER_SHOW'
const DRAWER_NOT_SHOW = 'DRAWER_NOT_SHOW'





export {
    CONTENT_NOT_SHOW ,
    DRAWER_NOT_SHOW,
    LOGIN_API_ERROR,
    CONTENT_SHOW,
    DRAWER_SHOW,
    LOGIN_API_REQUEST,
    LOGIN_API_SUCCESS,
    MAPDATA_API_ERROR,
    MAPDATA_API_REQUEST,
    MAPDATA_API_SUCCESS,
    SVG_CLICK,
    SVG_LOADED,
    SVG_UNLOADED
}